runmode: debug # 开发模式, debug, release, test
addr: :6060 # HTTP绑定端口
name: banner_man_server # API Server的名字
url: http://127.0.0.1:6060 # pingServer函数请求的API服务器的ip:port
max_ping_count: 10 # pingServer函数try的次数
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/banner_man_server.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: banner_man_db
  addr: mongodb://127.0.0.1:27017
  username: root
  password: root
project:
  name: banner_man_builder
  url: http://127.0.0.1:3080

packages:
  name: banner_man_packages
  api: http://npm.bannerman.club/-/verdaccio/packages
